// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: core/proto/point.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PointStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Payload       map[string]*Value      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointStruct) Reset() {
	*x = PointStruct{}
	mi := &file_core_proto_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointStruct) ProtoMessage() {}

func (x *PointStruct) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointStruct.ProtoReflect.Descriptor instead.
func (*PointStruct) Descriptor() ([]byte, []int) {
	return file_core_proto_point_proto_rawDescGZIP(), []int{0}
}

func (x *PointStruct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PointStruct) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *PointStruct) GetPayload() map[string]*Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_BoolValue
	//	*Value_BytesValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_core_proto_point_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_point_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_core_proto_point_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_IntValue) isValue_Value() {}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_BytesValue) isValue_Value() {}

type ScoredPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Payload       map[string]*Value      `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredPoint) Reset() {
	*x = ScoredPoint{}
	mi := &file_core_proto_point_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredPoint) ProtoMessage() {}

func (x *ScoredPoint) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_point_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredPoint.ProtoReflect.Descriptor instead.
func (*ScoredPoint) Descriptor() ([]byte, []int) {
	return file_core_proto_point_proto_rawDescGZIP(), []int{2}
}

func (x *ScoredPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScoredPoint) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ScoredPoint) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoredPoint) GetPayload() map[string]*Value {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Match         *MatchValue            `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_core_proto_point_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_point_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_core_proto_point_proto_rawDescGZIP(), []int{3}
}

func (x *Condition) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Condition) GetMatch() *MatchValue {
	if x != nil {
		return x.Match
	}
	return nil
}

type MatchValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MatchValue_StringValue
	//	*MatchValue_IntValue
	//	*MatchValue_DoubleValue
	//	*MatchValue_BoolValue
	//	*MatchValue_BytesValue
	Value         isMatchValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchValue) Reset() {
	*x = MatchValue{}
	mi := &file_core_proto_point_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchValue) ProtoMessage() {}

func (x *MatchValue) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_point_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchValue.ProtoReflect.Descriptor instead.
func (*MatchValue) Descriptor() ([]byte, []int) {
	return file_core_proto_point_proto_rawDescGZIP(), []int{4}
}

func (x *MatchValue) GetValue() isMatchValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MatchValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*MatchValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *MatchValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*MatchValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MatchValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*MatchValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *MatchValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*MatchValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *MatchValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*MatchValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isMatchValue_Value interface {
	isMatchValue_Value()
}

type MatchValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type MatchValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MatchValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type MatchValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type MatchValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*MatchValue_StringValue) isMatchValue_Value() {}

func (*MatchValue_IntValue) isMatchValue_Value() {}

func (*MatchValue_DoubleValue) isMatchValue_Value() {}

func (*MatchValue_BoolValue) isMatchValue_Value() {}

func (*MatchValue_BytesValue) isMatchValue_Value() {}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Must          []*Condition           `protobuf:"bytes,1,rep,name=must,proto3" json:"must,omitempty"`
	MustNot       []*Condition           `protobuf:"bytes,2,rep,name=must_not,json=mustNot,proto3" json:"must_not,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_core_proto_point_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_point_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_core_proto_point_proto_rawDescGZIP(), []int{5}
}

func (x *Filter) GetMust() []*Condition {
	if x != nil {
		return x.Must
	}
	return nil
}

func (x *Filter) GetMustNot() []*Condition {
	if x != nil {
		return x.MustNot
	}
	return nil
}

var File_core_proto_point_proto protoreflect.FileDescriptor

const file_core_proto_point_proto_rawDesc = "" +
	"\n" +
	"\x16core/proto/point.proto\x12\x04core\"\xb8\x01\n" +
	"\vPointStruct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x128\n" +
	"\apayload\x18\x03 \x03(\v2\x1e.core.PointStruct.PayloadEntryR\apayload\x1aG\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.core.ValueR\x05value:\x028\x01\"\xbd\x01\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"\xd0\x01\n" +
	"\vScoredPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x128\n" +
	"\apayload\x18\x04 \x03(\v2\x1e.core.ScoredPoint.PayloadEntryR\apayload\x1aG\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.core.ValueR\x05value:\x028\x01\"E\n" +
	"\tCondition\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05match\x18\x02 \x01(\v2\x10.core.MatchValueR\x05match\"\xc2\x01\n" +
	"\n" +
	"MatchValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"Y\n" +
	"\x06Filter\x12#\n" +
	"\x04must\x18\x01 \x03(\v2\x0f.core.ConditionR\x04must\x12*\n" +
	"\bmust_not\x18\x02 \x03(\v2\x0f.core.ConditionR\amustNotB*Z(github.com/DotNetAge/govector/core/protob\x06proto3"

var (
	file_core_proto_point_proto_rawDescOnce sync.Once
	file_core_proto_point_proto_rawDescData []byte
)

func file_core_proto_point_proto_rawDescGZIP() []byte {
	file_core_proto_point_proto_rawDescOnce.Do(func() {
		file_core_proto_point_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_point_proto_rawDesc), len(file_core_proto_point_proto_rawDesc)))
	})
	return file_core_proto_point_proto_rawDescData
}

var file_core_proto_point_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_core_proto_point_proto_goTypes = []any{
	(*PointStruct)(nil), // 0: core.PointStruct
	(*Value)(nil),       // 1: core.Value
	(*ScoredPoint)(nil), // 2: core.ScoredPoint
	(*Condition)(nil),   // 3: core.Condition
	(*MatchValue)(nil),  // 4: core.MatchValue
	(*Filter)(nil),      // 5: core.Filter
	nil,                 // 6: core.PointStruct.PayloadEntry
	nil,                 // 7: core.ScoredPoint.PayloadEntry
}
var file_core_proto_point_proto_depIdxs = []int32{
	6, // 0: core.PointStruct.payload:type_name -> core.PointStruct.PayloadEntry
	7, // 1: core.ScoredPoint.payload:type_name -> core.ScoredPoint.PayloadEntry
	4, // 2: core.Condition.match:type_name -> core.MatchValue
	3, // 3: core.Filter.must:type_name -> core.Condition
	3, // 4: core.Filter.must_not:type_name -> core.Condition
	1, // 5: core.PointStruct.PayloadEntry.value:type_name -> core.Value
	1, // 6: core.ScoredPoint.PayloadEntry.value:type_name -> core.Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_core_proto_point_proto_init() }
func file_core_proto_point_proto_init() {
	if File_core_proto_point_proto != nil {
		return
	}
	file_core_proto_point_proto_msgTypes[1].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_BytesValue)(nil),
	}
	file_core_proto_point_proto_msgTypes[4].OneofWrappers = []any{
		(*MatchValue_StringValue)(nil),
		(*MatchValue_IntValue)(nil),
		(*MatchValue_DoubleValue)(nil),
		(*MatchValue_BoolValue)(nil),
		(*MatchValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_point_proto_rawDesc), len(file_core_proto_point_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proto_point_proto_goTypes,
		DependencyIndexes: file_core_proto_point_proto_depIdxs,
		MessageInfos:      file_core_proto_point_proto_msgTypes,
	}.Build()
	File_core_proto_point_proto = out.File
	file_core_proto_point_proto_goTypes = nil
	file_core_proto_point_proto_depIdxs = nil
}
